# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"   

  - package-ecosystem: "nuget"
    directory: "/src/Episodes/Episodes.Api"
    schedule:
      interval: "weekly"    

  - package-ecosystem: "nuget"
    directory: "/src/Library/Library.Api"
    schedule:
      interval: "weekly"      

  - package-ecosystem: "nuget"
    directory: "/src/Movies/Movies.Api"
    schedule:
      interval: "weekly"      

  - package-ecosystem: "nuget"
    directory: "/src/Reader/Reader.Api"
    schedule:
      interval: "weekly" 

  - package-ecosystem: "nuget"
    directory: "/src/Episodes/Episodes.App"
    schedule:
      interval: "weekly"    

  - package-ecosystem: "nuget"
    directory: "/src/Library/Library.AppApi"
    schedule:
      interval: "weekly"      

  - package-ecosystem: "nuget"
    directory: "/src/Movies/Movies.App"
    schedule:
      interval: "weekly"      

  - package-ecosystem: "nuget"
    directory: "/src/Reader/Reader.App"
    schedule:
      interval: "weekly" 

  - package-ecosystem: "nuget"
    directory: "/src/PeterPedia.Functions"
    schedule:
      interval: "weekly"      

  - package-ecosystem: "nuget"
    directory: "/tests/PeterPedia.Tests"
    schedule:
      interval: "weekly"                    
      
  - package-ecosystem: "npm"
    directory: "/src/Episodes/Episodes.App"
    schedule:
      interval: "weekly"    

  - package-ecosystem: "npm"
    directory: "/src/Library/Library.App"
    schedule:
      interval: "weekly"      

  - package-ecosystem: "npm"
    directory: "/src/Movies/Movies.App"
    schedule:
      interval: "weekly"      

  - package-ecosystem: "npm"
    directory: "/src/Reader/Reader.App"
    schedule:
      interval: "weekly"                          
      
      
